variable "aws_region" {}
variable "aws_profile" {}
variable "vpc_id" {}
variable "pix_volume_size" {}
variable "pix_subnet_id" {}
variable "pix_instance_type" {}
variable "global_keypair" {}
variable "pix_volume_type" {}
variable "pix_ami" {}
variable "pix_ip" {}
variable "pix_cidr_blocks" {}
variable "jump_volume_size" {}
variable "jump_volume_type" {}
variable "jump_ami" {}
variable "jump_instance_type" {}
variable "jump_cidr_blocks" {}
variable "prod_private_us_east_1a" {}
variable "prod_private_us_east_1b" {}
variable "external_ips_allowed" {}
variable "global_availability_zones" {}
variable "global_product_tag" {}
variable "global_contact_tag" {}
variable "global_environment_tag" {}
